<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNrQcOVe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNrQcOVe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNrQcOVe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNrQcOVe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNrQcOVe\App_KernelDevDebugContainer([
    'container.build_hash' => 'NrQcOVe',
    'container.build_id' => '4805da7a',
    'container.build_time' => 1715176130,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNrQcOVe');
